const canvas=document.getElementById("gameCanvas");const ctx=canvas.getContext("2d");const dpr=window.devicePixelRatio||1;let vw=innerWidth;let vh=innerHeight;function resize(){vw=innerWidth;vh=innerHeight;canvas.width=Math.floor(vw*dpr);canvas.height=Math.floor(vh*dpr);canvas.style.width=vw+"px";canvas.style.height=vh+"px"}resize();addEventListener("resize",resize);
const healthEl=document.getElementById("health");const scoreEl=document.getElementById("score");const weaponEl=document.getElementById("weapon");const startBtn=document.getElementById("startBtn");const pauseBtn=document.getElementById("pauseBtn");const resumeBtn=document.getElementById("resumeBtn");const restartBtn=document.getElementById("restartBtn");const touchTarget=document.getElementById("touchTarget");
const keys={};addEventListener("keydown",e=>{if(["w","a","s","d","W","A","S","D"].includes(e.key))e.preventDefault();keys[e.key.toLowerCase()]=true});addEventListener("keyup",e=>{keys[e.key.toLowerCase()]=false});
let touchActive=false;let touchX=0;let touchY=0;function setTouch(x,y){touchActive=true;touchX=x;touchY=y;touchTarget.style.opacity="1";touchTarget.style.left=x+"px";touchTarget.style.top=y+"px"}function clearTouch(){touchActive=false;touchTarget.style.opacity="0"}addEventListener("touchstart",e=>{const t=e.touches[0];setTouch(t.clientX,t.clientY)});addEventListener("touchmove",e=>{const t=e.touches[0];setTouch(t.clientX,t.clientY)});addEventListener("touchend",()=>{clearTouch()});
const rand=(min,max)=>min+Math.random()*(max-min);const clamp=(v,min,max)=>v<min?min:v>max?max:v;
const audioCtx=typeof AudioContext!=="undefined"?new AudioContext():typeof webkitAudioContext!=="undefined"?new webkitAudioContext():null;let musicGain;let musicOsc;function playTone(f,d,g,type){if(!audioCtx)return;const osc=audioCtx.createOscillator();const gain=audioCtx.createGain();osc.type=type||"sine";osc.frequency.value=f;gain.gain.value=g;osc.connect(gain);gain.connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+d)}function shootSound(){playTone(680,0.04,0.08,"square")}function explosionSound(){playTone(80,0.2,0.15,"sawtooth")}function hurtSound(){playTone(220,0.08,0.12,"triangle")}function pickupSound(){playTone(1000,0.06,0.12,"square")}function startMusic(){if(!audioCtx)return;musicGain=audioCtx.createGain();musicGain.gain.value=0.05;musicOsc=audioCtx.createOscillator();musicOsc.type="sine";musicOsc.frequency.value=140;musicOsc.connect(musicGain);musicGain.connect(audioCtx.destination);musicOsc.start()}function stopMusic(){if(musicOsc)try{musicOsc.stop()}catch(e){}}
const state={running:false,gameOver:false,score:0,health:100,weaponLevel:1,weaponExpire:0,lastShot:0,spawnTimer:0,player:{x:vw/2,y:vh*0.8,speed:300,color:"#5cf5ff",flash:0},bullets:[],enemies:[],rewards:[]};
function reset(){state.running=false;state.gameOver=false;state.score=0;state.health=100;state.weaponLevel=1;state.weaponExpire=0;state.lastShot=0;state.spawnTimer=0;state.player.x=vw/2;state.player.y=vh*0.8;state.player.flash=0;state.bullets.length=0;state.enemies.length=0;state.rewards.length=0;updateHUD()}
function updateHUD(){healthEl.textContent=Math.floor(state.health);scoreEl.textContent=Math.floor(state.score);weaponEl.textContent=state.weaponLevel}
function startGame(){reset();state.running=true;startBtn.disabled=true;pauseBtn.disabled=false;resumeBtn.disabled=true;restartBtn.disabled=true;if(audioCtx&&audioCtx.state==="suspended")audioCtx.resume();startMusic();lastTime=performance.now();loop()}
function pauseGame(){if(!state.running)return;state.running=false;pauseBtn.disabled=true;resumeBtn.disabled=false;restartBtn.disabled=false;stopMusic()}
function resumeGame(){if(state.running||state.gameOver)return;state.running=true;pauseBtn.disabled=false;resumeBtn.disabled=true;restartBtn.disabled=true;if(audioCtx&&audioCtx.state==="suspended")audioCtx.resume();startMusic();lastTime=performance.now();loop()}
function endGame(){state.running=false;state.gameOver=true;pauseBtn.disabled=true;resumeBtn.disabled=true;restartBtn.disabled=false;stopMusic()}
function restartGame(){reset();startBtn.disabled=true;pauseBtn.disabled=false;resumeBtn.disabled=true;restartBtn.disabled=true;state.running=true;if(audioCtx&&audioCtx.state==="suspended")audioCtx.resume();startMusic();lastTime=performance.now();loop()}
startBtn.addEventListener("click",startGame);pauseBtn.addEventListener("click",pauseGame);resumeBtn.addEventListener("click",resumeGame);restartBtn.addEventListener("click",restartGame);
function movePlayer(dt){let vx=0,vy=0;if(keys["w"])vy-=1;if(keys["s"])vy+=1;if(keys["a"])vx-=1;if(keys["d"])vx+=1;if(touchActive){const tx=touchX*dpr;const ty=touchY*dpr;const dx=tx-state.player.x;const dy=ty-state.player.y;const m=Math.hypot(dx,dy);if(m>1){vx+=dx/m;vy+=dy/m}}const sp=state.player.speed;state.player.x=clamp(state.player.x+vx*sp*dt,20,canvas.width-20);state.player.y=clamp(state.player.y+vy*sp*dt,20,canvas.height-20)}
function shoot(dt,now){const cd=state.weaponLevel>=4?120:state.weaponLevel===3?160:200;if(now-state.lastShot<cd)return;state.lastShot=now;const x=state.player.x;const y=state.player.y-18;const base=400;const patterns={1:[0],2:[-0.06,0.06],3:[-0.14,0,0.14],4:[-0.22,-0.07,0.07,0.22],5:[-0.28,-0.14,0,0.14,0.28]};patterns[state.weaponLevel].forEach(a=>{state.bullets.push({x,y,vx:Math.sin(a)*base,vy:-Math.cos(a)*base,size:6,color:"#9cf5ff"})});shootSound()}
function spawnEnemy(dt){const rateBase=900;const rate=Math.max(250,rateBase- state.score*2);state.spawnTimer+=dt*1000;if(state.spawnTimer<rate)return;state.spawnTimer=0;const type=Math.random()<0.55?"plane":"meteor";const x=rand(30,canvas.width-30);const y=-40;const s=type==="plane"?rand(120,180):rand(60,120);const size=type==="plane"?18:22;const vx=rand(-40,40);const vy=s;state.enemies.push({type,x,y,vx,vy,size,hp:type==="plane"?2:3,color:type==="plane"?"#ffed5c":"#c7753a"})}
function updateBullets(dt){for(let i=state.bullets.length-1;i>=0;i--){const b=state.bullets[i];b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.y<-30||b.x<-30||b.x>canvas.width+30)state.bullets.splice(i,1)}}
function updateEnemies(dt){for(let i=state.enemies.length-1;i>=0;i--){const e=state.enemies[i];e.x+=e.vx*dt;e.y+=e.vy*dt;if(e.y>canvas.height+40)state.enemies.splice(i,1)}}
function dropReward(ex,ey,type){const p=Math.random();let r=null;if(type==="plane"){r=p<0.8?"weapon":"heal"}else{r=p<0.7?"heal":"weapon"}if(Math.random()<0.3)state.rewards.push({x:ex,y:ey,vy:60,type:r,size:12,color:r==="heal"?"#7cff80":"#ff78e1"})}
function collisions(){for(let i=state.enemies.length-1;i>=0;i--){const e=state.enemies[i];for(let j=state.bullets.length-1;j>=0;j--){const b=state.bullets[j];const dx=e.x-b.x;const dy=e.y-b.y;const d=Math.hypot(dx,dy);if(d<e.size+b.size){state.bullets.splice(j,1);e.hp-=1;if(e.hp<=0){state.enemies.splice(i,1);state.score+=10;explosionSound();dropReward(e.x,e.y,e.type);break}}}}for(let i=state.enemies.length-1;i>=0;i--){const e=state.enemies[i];const dx=e.x-state.player.x;const dy=e.y-state.player.y;const d=Math.hypot(dx,dy);if(d<e.size+16){state.enemies.splice(i,1);const dmg=e.type==="plane"?15:10;state.health-=dmg;state.player.flash=0.18;hurtSound();if(state.health<=0){state.health=0;endGame()}}}for(let i=state.rewards.length-1;i>=0;i--){const r=state.rewards[i];r.y+=r.vy*dt;const dx=r.x-state.player.x;const dy=r.y-state.player.y;const d=Math.hypot(dx,dy);if(d<r.size+18){state.rewards.splice(i,1);pickupSound();if(r.type==="heal"){state.health=Math.min(100,state.health+25)}else{state.weaponLevel=Math.min(5,state.weaponLevel+1);state.weaponExpire=performance.now()+5000}}else if(r.y>canvas.height+30){state.rewards.splice(i,1)}}}
function drawShip(x,y,c){ctx.save();ctx.translate(x,y);ctx.beginPath();ctx.moveTo(0,-16);ctx.lineTo(12,12);ctx.lineTo(-12,12);ctx.closePath();ctx.fillStyle=c;ctx.fill();ctx.restore()}
function drawEnemy(e){ctx.beginPath();if(e.type==="meteor"){ctx.arc(e.x,e.y,e.size,0,Math.PI*2);ctx.fillStyle=e.color;ctx.fill()}else{ctx.save();ctx.translate(e.x,e.y);ctx.rotate(Math.PI/4);ctx.fillStyle=e.color;ctx.fillRect(-e.size/1.2,-e.size/1.2,e.size*1.2,e.size*1.2);ctx.restore()}}
function drawBullet(b){ctx.beginPath();ctx.arc(b.x,b.y,b.size,0,Math.PI*2);ctx.fillStyle=b.color;ctx.fill()}
function drawReward(r){ctx.beginPath();if(r.type==="heal"){ctx.fillStyle=r.color;ctx.arc(r.x,r.y,r.size,0,Math.PI*2);ctx.fill()}else{ctx.save();ctx.translate(r.x,r.y);ctx.rotate(Math.PI/4);ctx.fillStyle=r.color;ctx.fillRect(-r.size/1.6,-r.size/1.6,r.size*1.6,r.size*1.6);ctx.restore()}}
function bgStars(){ctx.fillStyle="#0b0f1a";ctx.fillRect(0,0,canvas.width,canvas.height);for(let i=0;i<80;i++){const x=((i*97)%canvas.width);const y=((i*53+starPhase)%canvas.height);ctx.fillStyle=i%7===0?"#ffffff":"#a6b9ff";ctx.fillRect(x,y,2,2)}}let starPhase=0;
function applyWeaponExpire(now){if(state.weaponExpire&&now>state.weaponExpire){state.weaponExpire=0;state.weaponLevel=1}}
let lastTime=0;function loop(){if(!state.running)return;const now=performance.now();const dt=Math.min(0.033,(now-lastTime)/1000)||0.016;lastTime=now;starPhase+=60*dt;applyWeaponExpire(now);movePlayer(dt);shoot(dt,now);updateBullets(dt);updateEnemies(dt);collisions();updateHUD();ctx.save();ctx.scale(dpr,dpr);bgStars();state.rewards.forEach(drawReward);state.enemies.forEach(drawEnemy);state.bullets.forEach(drawBullet);let color=state.player.color;if(state.player.flash>0){state.player.flash-=dt;color="#ff5c5c"}drawShip(state.player.x/dpr,state.player.y/dpr,color);ctx.restore();spawnEnemy(dt);if(!state.gameOver)requestAnimationFrame(loop)}
